async function generate_default(nome, link, nome_consumidor, quantidade, data, distancia, consumo, emissao, classificacao) {

    var mail_body="";
    mail_body += "<!DOCTYPE html>";
    mail_body += "<html lang=\"en\">";
    mail_body += "<head>";
    mail_body += "    <meta charset=\"UTF-8\">";
    mail_body += "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
    mail_body += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
    mail_body += "    <link rel=\"stylesheet\" href=\"https:\/\/cdn.jsdelivr.net\/npm\/bootstrap-icons@1.8.3\/font\/bootstrap-icons.css\">";
    mail_body += "    <title>Email Transportador Baylit<\/title>";
    mail_body += "<style>";
    mail_body += "        *{";
    mail_body += "            font-family: sans-serif;";
    mail_body += "            padding: 0;";
    mail_body += "            \/* margin: 0; *\/";
    mail_body += "        }";
    mail_body += " ";
    mail_body += "        section{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            top: 10px;";
    mail_body += "            width: calc(100% - 100px);";
    mail_body += "            height: fit-content;";
    mail_body += "            padding-bottom: 80px;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "        }";
    mail_body += "        header{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            margin-bottom: 35px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            margin-bottom: 40px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            height: 30px;";
    mail_body += "            width: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img:first-child{";
    mail_body += "            margin-right: 10px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .mensagemPrincipalMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 20px;";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .descricaoMensagemPrincipal{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            color: rgb(117, 117, 117);";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            min-width: 120px;";
    mail_body += "            white-space: nowrap;";
    mail_body += "            padding: 10px 35px;";
    mail_body += "            border: none;";
    mail_body += "            border-radius: 4px;";
    mail_body += "            background-color: black;";
    mail_body += "            color: white;";
    mail_body += "            font-size: 11px;";
    mail_body += "            text-transform: uppercase;";
    mail_body += "            cursor: pointer;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit:hover{";
    mail_body += "            background-color: rgba(0, 0, 0, 0.9);";
    mail_body += "        }";
    mail_body += "";
    mail_body += "";
    mail_body += "        \/* ---------- ENCOMENDAS ---------- *\/";
    mail_body += "";
    mail_body += "        .bodyTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height:fit-content;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .tituloTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            font-size: 16px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            vertical-align: top;";
    mail_body += "            margin-bottom: 30px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .datasTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            width: 100%;";
    mail_body += "            height: 60px;";
    mail_body += "            background-color: rgb(244, 244, 244, 0.5);";
    mail_body += "            border-radius: 3px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .dataEspecificaTransporteMail{";
    mail_body += "             position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            width: 32%;";
    mail_body += "            height: 60px;";
    mail_body += "            text-align: center;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .dataEspecificaTransporteMail i{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            top: 1px;";
    mail_body += "            -webkit-text-stroke: .4px;";
    mail_body += "        }";
    mail_body += "        .dataEspecificaTransporteMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            font-size: 13px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .dataEspecificaTransporteMail h4{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            font-size: 15px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .paddingTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            background-color: rgb(244, 244, 244, 0.5);";
    mail_body += "            border-radius: 3px;";
    mail_body += "            margin-top: 15px;";
    mail_body += "            \/* padding: 15px; *\/";
    mail_body += "        }";
    mail_body += "        .detailsTransporteHeaderMail{";
    mail_body += "            position: relative;";
    mail_body += "            width: calc(100% - 20px);";
    mail_body += "            padding-top: 10px;";
    mail_body += "            padding-bottom: 10px;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailsTransporteHeaderMail h6{";
    mail_body += "           position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-bottom: 8px;";
    mail_body += "            font-size: 12px;";
    mail_body += "            font-weight: 600;";
    mail_body += "            color: rgb(145, 145, 145);";
    mail_body += "            \/* margin-top: 15px; *\/";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailsTransporteHeaderMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-top: 5px;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailsTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: calc(100% - 20px);";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            grid-gap: 10px;";
    mail_body += "            margin-top: 10px;";
    mail_body += "            margin-bottom: 10px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailTransporteMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            width: 24%;";
    mail_body += "            height: 60px;";
    mail_body += "            text-align: center;";
    mail_body += "        }";
    mail_body += "        .detailTransporteMail h6{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "            color: rgb(145, 145, 145);";
    mail_body += "        }";
    mail_body += "        .detailTransporteMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        @media screen and (max-width: 900px){";
    mail_body += "";
    mail_body += "        .datasTransporteMail{";
    mail_body += "            height: 50px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .dataEspecificaTransporteMail{";
    mail_body += "            display:block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: 50px;";
    mail_body += "        }";
    mail_body += "        section{";
    mail_body += "            width: calc(100% - 30px);";
    mail_body += "        }";
    mail_body += "        }";
    mail_body += "    <\/style>";
    mail_body += "<\/head>";
    mail_body += "<body>";
    mail_body += "    <section>";
    mail_body += "        <header>";
    mail_body += "            <div class=\"marcaBaylitMail\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/logoBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/wordBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "            <\/div>";
    mail_body += "            <h1 class=\"mensagemPrincipalMail\">Foi adicionado um novo pedido a um dos teus transportes.<\/h1>";
    mail_body += "            <p class=\"descricaoMensagemPrincipal\">";
    mail_body += "                Caro(a) "+nome+", ";
    mail_body += "                <br>";
    mail_body += "                Podes encontrar mais informações na aqui:";
    mail_body += "            <\/p>";
    mail_body += "            <a href='"+link+"'><button class=\"btnToBaylit\">Ver pedido<\/button><\/a>";
    mail_body += "        <\/header>";
    mail_body += "";
    mail_body += "        <div class=\"bodyTransporteMail\">";
    mail_body += "            <h1 class=\"tituloTransporteMail\">";
    mail_body += "                O utilizador "+nome_consumidor+" adicionou "+quantidade+" novos itens ao teu transporte.";
    mail_body += "            <\/h1>";
    mail_body += "            <div class=\"datasTransporteMail\">";
    mail_body += "                <div class=\"dataEspecificaTransporteMail\">";
    mail_body += "                    <i class=\"bi bi-calendar3-range\"><\/i>";
    mail_body += "                    <h5>Data de transporte<\/h5>";
    mail_body += "                    <h4>"+data+"<\/h4>";
    mail_body += "                <\/div>";
    mail_body += "            <\/div>";
    mail_body += "            <div class=\"paddingTransporteMail\">";
    mail_body += "                <div class=\"detailsTransporteHeaderMail\">";
    mail_body += "                    <h6>Transportador<\/h6>";
    mail_body += "                    <h5>"+nome+"<\/h5>";
    mail_body += "                <\/div>";
    mail_body += "                <div class=\"detailsTransporteMail\">";
    mail_body += "                    <div class=\"detailTransporteMail\">";
    mail_body += "                        <h6>Distancia total de transporte<\/h6>";
    mail_body += "                        <h5>"+distancia+"KM<\/h5>";
    mail_body += "                    <\/div>";
    mail_body += "                    <div class=\"detailTransporteMail\">";
    mail_body += "                        <h6>Consumo por item<\/h6>";
    mail_body += "                        <h5>"+consumo+"L<\/h5>";
    mail_body += "                    <\/div>";
    mail_body += "                    <div class=\"detailTransporteMail\">";
    mail_body += "                        <h6>Emissão por item<\/h6>";
    mail_body += "                        <h5>"+emissao+"g<\/h5>";
    mail_body += "                    <\/div>";
    mail_body += "                    <div class=\"detailTransporteMail\">";
    mail_body += "                        <h6>Classificação do transporte<\/h6>";
    mail_body += "                        <h5>"+classificacao+"<\/h5>";
    mail_body += "                    <\/div>";
    mail_body += "                <\/div>";
    mail_body += "            <\/div>";
    mail_body += "            <p class=\"descricaoMensagemPrincipal\">";
    mail_body += "                Podes encontrar mais informações na aqui:";
    mail_body += "            <\/p>";
    mail_body += "            <a href='"+link+"'><button class=\"btnToBaylit\">Ver pedido<\/button><\/a>";
    mail_body += "        <\/div>";
    mail_body += "    <\/section>";
    mail_body += "<\/body>";
    mail_body += "<\/html>";
        
        


    return mail_body
}

module.exports = {
    generate_default
}