async function generate_default(nome, link, nome_consumidor, valor_compra, nome_produto,
     nome_subcategoria, atributos, rating, quantidade, preco, fotografia) {

    var mail_body="";
    mail_body += "<!DOCTYPE html>";
    mail_body += "<html lang=\"en\">";
    mail_body += "<head>";
    mail_body += "    <meta charset=\"UTF-8\">";
    mail_body += "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
    mail_body += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
    mail_body += "    <link rel=\"stylesheet\" href=\"https:\/\/cdn.jsdelivr.net\/npm\/bootstrap-icons@1.8.3\/font\/bootstrap-icons.css\">";
    mail_body += "    <title>Email Fornecedor Baylit<\/title>";
    mail_body += "<style>";
    mail_body += "        *{";
    mail_body += "            font-family: sans-serif;";
    mail_body += "            padding: 0;";
    mail_body += "            \/* margin: 0; *\/";
    mail_body += "        }";
    mail_body += "        ";
    mail_body += "        section{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            top: 10px;";
    mail_body += "            width: calc(100% - 100px);";
    mail_body += "            height: fit-content;";
    mail_body += "            padding-bottom: 80px;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "        }";
    mail_body += "        header{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            margin-bottom: 35px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            margin-bottom: 40px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            height: 30px;";
    mail_body += "            width: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img:first-child{";
    mail_body += "            margin-right: 10px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .mensagemPrincipalMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 20px;";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .descricaoMensagemPrincipal{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            color: rgb(117, 117, 117);";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            min-width: 120px;";
    mail_body += "            white-space: nowrap;";
    mail_body += "            padding: 10px 35px;";
    mail_body += "            border: none;";
    mail_body += "            border-radius: 4px;";
    mail_body += "            background-color: black;";
    mail_body += "            color: white;";
    mail_body += "            font-size: 11px;";
    mail_body += "            text-transform: uppercase;";
    mail_body += "            cursor: pointer;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit:hover{";
    mail_body += "            background-color: rgba(0, 0, 0, 0.9);";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        \/* ---------- ENCOMENDAS ---------- *\/";
    mail_body += "";
    mail_body += "        .bodyFornecedorMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height:fit-content;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .tituloFornecedorMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            font-size: 16px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            vertical-align: top;";
    mail_body += "            margin-bottom: 30px;";
    mail_body += "        }";
    mail_body += "        ";
    mail_body += "";
    mail_body += "        .paddingFornecedorMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            background-color: rgb(244, 244, 244, 0.5);";
    mail_body += "            border-radius: 3px;";
    mail_body += "            margin-top: 15px;";
    mail_body += "        }";
    mail_body += "        .detailsFornecedorMail{";
    mail_body += "            position: relative;";
    mail_body += "            width: calc(100% - 20px);";
    mail_body += "            padding-top: 10px;";
    mail_body += "            padding-bottom: 10px;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailsFornecedorMail h6{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-bottom: 8px;";
    mail_body += "            font-size: 12px;";
    mail_body += "            font-weight: 600;";
    mail_body += "            color: rgb(145, 145, 145);";
    mail_body += "            \/* margin-top: 15px; *\/";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .detailsFornecedorMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-top: 5px;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .displayerProdutosMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: calc(100% - 20px);";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            margin-top: 10px;";
    mail_body += "            margin-bottom: 10px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .produtoMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-bottom: 15px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .produtoMail:last-child{";
    mail_body += "            margin-bottom: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .fotoProductMail,";
    mail_body += "        .nomeProductMail,";
    mail_body += "        .atributosProductMail,";
    mail_body += "        .nivelProductMail,";
    mail_body += "        .quantidadeProductMail,";
    mail_body += "        .precoProductMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            height: 100px;";
    mail_body += "            overflow: hidden;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .fotoProductMail{";
    mail_body += "            background-color: rgba(209, 209, 209, 0.5);";
    mail_body += "            width: 100px;";
    mail_body += "        }";
    mail_body += "        .nomeProductMail{";
    mail_body += "            width: fit-content;";
    mail_body += "            max-width: 120px;";
    mail_body += "        }";
    mail_body += "        .atributosProductMail{";
    mail_body += "            width: calc(100% - 500px);";
    mail_body += "        }";
    mail_body += "        .nivelProductMail{";
    mail_body += "            width: 90px;";
    mail_body += "        }";
    mail_body += "        .quantidadeProductMail{";
    mail_body += "            width: 90px;";
    mail_body += "        }";
    mail_body += "        .precoProductMail{";
    mail_body += "            width: 90px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .fotoProductMail img{";
    mail_body += "            position: absolute;";
    mail_body += "            top: 50%;";
    mail_body += "            left: 50%;";
    mail_body += "            transform: translate(-50%, -50%);";
    mail_body += "            height: 100%;";
    mail_body += "            width: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .nomeProductMail h4{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-bottom: 3px;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            text-transform: uppercase;";
    mail_body += "            top: 50%;";
    mail_body += "            transform: translateY(-110%);";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .nomeProductMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "            font-size: 11px;";
    mail_body += "            font-weight: 600;";
    mail_body += "            color: rgb(145, 145, 145);";
    mail_body += "            top: 50%;";
    mail_body += "            transform: translateY(-110%);";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .atributosProductMail h4{";
    mail_body += "            position: relative;";
    mail_body += "            width: 100%;";
    mail_body += "            overflow: hidden;";
    mail_body += "            text-overflow: ellipsis;";
    mail_body += "            white-space: nowrap;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            top: 50%;";
    mail_body += "            transform: translateY(-100%);";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .nivelProductMail,";
    mail_body += "        .quantidadeProductMail,";
    mail_body += "        .precoProductMail{";
    mail_body += "            text-align: center;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .nivelProductMail h5,";
    mail_body += "        .quantidadeProductMail h5,";
    mail_body += "        .precoProductMail h5{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "            font-size: 11px;";
    mail_body += "            font-weight: 600;";
    mail_body += "            color: rgb(145, 145, 145);";
    mail_body += "            top: 50%;";
    mail_body += "            transform: translateY(-110%);";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .nivelProductMail h4,";
    mail_body += "        .quantidadeProductMail h4,";
    mail_body += "        .precoProductMail h4{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin: 0;";
    mail_body += "            margin-top: 3px;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            top: 50%;";
    mail_body += "            transform: translateY(-110%);";
    mail_body += "            margin: 0;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        @media screen and (max-width: 900px){";
    mail_body += "";
    mail_body += "            .fotoProductMail{";
    mail_body += "            width: 100px;";
    mail_body += "            }";
    mail_body += "            .nomeProductMail{";
    mail_body += "                width: fit-content;";
    mail_body += "                max-width: 120px;";
    mail_body += "            }";
    mail_body += "            .atributosProductMail{";
    mail_body += "                width: calc(100% - 230px);";
    mail_body += "            }";
    mail_body += "            .nivelProductMail{";
    mail_body += "                width: 100px;";
    mail_body += "            }";
    mail_body += "            .quantidadeProductMail{";
    mail_body += "                width: 100px;";
    mail_body += "            }";
    mail_body += "            .precoProductMail{";
    mail_body += "                width: 100px;";
    mail_body += "            }";
    mail_body += "";
    mail_body += "            section{";
    mail_body += "            width: calc(100% - 30px);";
    mail_body += "        }";
    mail_body += "        }";
    mail_body += "    <\/style>";
    mail_body += "<\/head>";
    mail_body += "<body>";
    mail_body += "    <section>";
    mail_body += "        <header>";
    mail_body += "            <div class=\"marcaBaylitMail\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/logoBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/wordBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "            <\/div>";
    mail_body += "            <h1 class=\"mensagemPrincipalMail\">Nova venda efetuada.<\/h1>";
    mail_body += "            <p class=\"descricaoMensagemPrincipal\">";
    mail_body += "                Caro(a) "+nome+", ";
    mail_body += "                <br>";
    mail_body += "                Podes encontrar mais informações aqui:";
    mail_body += "            <\/p>";
    mail_body += "            <a href='"+link+"'><button class=\"btnToBaylit\">Ver venda<\/button><\/a>";
    mail_body += "        <\/header>";
    mail_body += "";
    mail_body += "        <div class=\"bodyFornecedorMail\">";
    mail_body += "            <h1 class=\"tituloFornecedorMail\">";
    mail_body += "                Utilizador "+nome_consumidor+" acabou de comprar "+valor_compra+"€ em produtos da sua loja.";
    mail_body += "            <\/h1>";
    mail_body += "            ";
    mail_body += "            <div class=\"paddingFornecedorMail\">";
    mail_body += "                <div class=\"detailsFornecedorMail\">";
    mail_body += "                    <h6>Produto vendido<\/h6>";
    mail_body += "                <\/div>";
    mail_body += "                <div class=\"displayerProdutosMail\">";
    mail_body += "                    <div class=\"produtoMail\">";
    mail_body += "                        <div class=\"fotoProductMail\">";
    mail_body += "                            <img src=\""+fotografia+"\" alt=\"produto baylit\">";
    mail_body += "                        <\/div>";
    mail_body += "                        <div class=\"nomeProductMail\">";
    mail_body += "                            <h4>"+nome_produto+"<\/h4>";
    mail_body += "                            <h5>"+nome_subcategoria+"<\/h5>";
    mail_body += "                        <\/div>";
    mail_body += "                        <div class=\"atributosProductMail\">";
    mail_body += "                            <h4>";
    for (let atributo of atributos) {
        if (atributo == atributos[0]) {
            mail_body += atributo
        } else {
            mail_body += ", " + atributo
        }
    }
    mail_body += "                            <\/h4>";
    mail_body += "                        <\/div>";
    mail_body += "                        <div class=\"nivelProductMail\">";
    mail_body += "                            <h5>Sustentabilidade<\/h5>";
    mail_body += "                            <h4>"+rating+"<\/h4>";
    mail_body += "                        <\/div>";
    mail_body += "                        <div class=\"quantidadeProductMail\">";
    mail_body += "                            <h5>Quantidade<\/h5>";
    mail_body += "                            <h4>"+quantidade+"<\/h4>";
    mail_body += "                        <\/div>";
    mail_body += "                        <div class=\"precoProductMail\">";
    mail_body += "                            <h5>Preço total<\/h5>";
    mail_body += "                            <h4>"+preco+"€<\/h4>";
    mail_body += "                        <\/div>";
    mail_body += "                    <\/div>";
    mail_body += "                <\/div>";
    mail_body += "            <\/div>";
    mail_body += "            <p class=\"descricaoMensagemPrincipal\">";
    mail_body += "                Podes encontrar mais informações aqui:";
    mail_body += "            <\/p>";
    mail_body += "            <a href='"+link+"'><button class=\"btnToBaylit\">Ver venda<\/button><\/a>";
    mail_body += "        <\/div>";
    mail_body += "    <\/section>";
    mail_body += "<\/body>";
    mail_body += "<\/html>";
        


    return mail_body
}

module.exports = {
    generate_default
}