async function generate_default(title, mensagem_principal, texto, nome, link) {
    var mail_body="";
    mail_body += "<!DOCTYPE html>";
    mail_body += "<html lang=\"en\">";
    mail_body += "<head>";
    mail_body += "    <meta charset=\"UTF-8\">";
    mail_body += "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
    mail_body += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
    mail_body += "    <title>"+title+"<\/title>";
    mail_body += "    <style>";
    mail_body += "        *{";
    mail_body += "            font-family: sans-serif;";
    mail_body += "            padding: 0;";
    mail_body += "        }";
    mail_body += " ";
    mail_body += "        section{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            top: 10px;";
    mail_body += "            width: calc(100% - 100px);";
    mail_body += "            height: fit-content;";
    mail_body += "            padding-bottom: 80px;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "        }";
    mail_body += "        header{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            margin-bottom: 35px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: fit-content;";
    mail_body += "            height: fit-content;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            margin-bottom: 40px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img{";
    mail_body += "            position: relative;";
    mail_body += "            display: inline-block;";
    mail_body += "            height: 30px;";
    mail_body += "            width: auto;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .marcaBaylitMail img:first-child{";
    mail_body += "            margin-right: 10px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .mensagemPrincipalMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 20px;";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .descricaoMensagemPrincipal{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            text-align: center;";
    mail_body += "            height: fit-content;";
    mail_body += "            font-size: 13px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            color: rgb(117, 117, 117);";
    mail_body += "            margin-top: 30px;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            margin-left: auto;";
    mail_body += "            margin-right: auto;";
    mail_body += "            min-width: 120px;";
    mail_body += "            white-space: nowrap;";
    mail_body += "            padding: 10px 35px;";
    mail_body += "            border: none;";
    mail_body += "            border-radius: 4px;";
    mail_body += "            background-color: black;";
    mail_body += "            color: white;";
    mail_body += "            font-size: 11px;";
    mail_body += "            text-transform: uppercase;";
    mail_body += "            cursor: pointer;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .btnToBaylit:hover{";
    mail_body += "            background-color: rgba(0, 0, 0, 0.9);";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .tituloDefaultMail{";
    mail_body += "            position: relative;";
    mail_body += "            display: block;";
    mail_body += "            width: 100%;";
    mail_body += "            height: fit-content;";
    mail_body += "            text-align: center;";
    mail_body += "            font-size: 16px;";
    mail_body += "            font-weight: 500;";
    mail_body += "            vertical-align: top;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        .tituloDefaultMail span{";
    mail_body += "            font-weight: 600;";
    mail_body += "        }";
    mail_body += "";
    mail_body += "        @media screen and (max-width: 850px){";
    mail_body += "            section{";
    mail_body += "            width: calc(100% - 30px);";
    mail_body += "        }";
    mail_body += "        }";
    mail_body += "    <\/style>";
    mail_body += "<\/head>";
    mail_body += "<body>";
    mail_body += "    <section>";
    mail_body += "        <header>";
    mail_body += "            <div class=\"marcaBaylitMail\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/logoBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "                <img src=\"https:\/\/baylit-images.s3.eu-west-3.amazonaws.com\/baylit\/wordBaylit.png\" alt=\"logotipo baylit\">";
    mail_body += "            <\/div>";
    mail_body += "            <h1 class=\"mensagemPrincipalMail\">"+mensagem_principal+"<\/h1>";
    mail_body += "            <h1 class=\"tituloDefaultMail\">";
    mail_body += "                "+texto+"";
    mail_body += "            <\/h1>";
    mail_body += "            <p class=\"descricaoMensagemPrincipal\">";
    mail_body += "                Caro(a) "+nome+", ";
    mail_body += "                <br>";
    mail_body += "                Podes encontrar mais informações na nossa página aqui:";
    mail_body += "            <\/p>";
    mail_body += "            <a href='"+link+"'><button class=\"btnToBaylit\">BayLit<\/button>";
    mail_body += "        <\/header>";
    mail_body += "";
    mail_body += "        ";
    mail_body += "    <\/section>";
    mail_body += "<\/body>";
    mail_body += "<\/html>";

    return mail_body
}

module.exports = {
    generate_default
}